CREATE_SHOW = "CREATE_SHOW"
REMOVE_SHOW = "REMOVE_SHOW"
SEARCH_HUMMINGBIRD = "SEARCH_HUMMINGBIRD"
REGISTER_SHOW = "REGISTER_SHOW"

module.exports = {
  CREATE_SHOW,
  REMOVE_SHOW,
  SEARCH_HUMMINGBIRD,
  REGISTER_SHOW
}
